<?php

/**
 * @file
 * Keeps a list of Belgian Postal codes to use as a field.
 */

/**
 * Implements hook_entity_info().
 */
function belpost_entity_info() {
  $info = array();
  $info['BelPost'] = array(
    'label' => t('Belgian Postal code'),
    'base table' => 'belpost',
    'entity keys' => array(
      'id' => 'id',
      'label' => 'citynl',
    ),
    'uri callback' => 'entity_class_uri',
    'entity class' => 'BelPostEntity',
    'controller class' => 'BelPostEntityAPIController',
    'admin ui' => array(
      'path' => 'admin/belpost',
      'menu wildcard' => '%belpost',
      'file' => 'belpost.admin.inc',
    ),
    'module' => 'belpost',
    'access callback' => 'belpost_access',
    'view modes' => array(
      'full' => array(
        'label' => t('Full'),
        'custom settings' => FALSE,
      ),
      'field' => array(
        'label' => t('Field'),
        'custom settings' => FALSE,
      ),
    ),
  );
  return $info;
}

/**
 * Implements hook_menu().
 */
function belpost_menu() {
  $items = array();
  $items['belpost/%belpost'] = array(
    'title' => 'code',
    'page callback' => 'belpost_view_code',
    'page arguments' => array(1),
    'access arguments' => array('view belpost'),
  );
  $items['belpost/autocomplete'] = array(
    'title' => 'belpost autocomplete',
    'page callback' => 'belpost_autocomplete',
    'page arguments' => array(2),
    'access arguments' => array('view belpost'),
    'type' => MENU_CALLBACK,
  );
  $items['admin/belpost/settings'] = array(
    'title' => 'Belgian Postal Code administration',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('belpost_admin'),
    'access arguments' => array('administer belpost'),
  );
  return $items;
}

/**
 * Checks whether the user has access to the required operation.
 * 
 * @param string $op
 *   An operation
 * @param object $entity
 *   The entity the operation must be performed on
 * @param object $account
 *   The account that tries to perform the operation
 * 
 * @return bool
 *   TRUE when operation is allowed, FALSE if otherwise
 */
function belpost_access($op, $entity = NULL, $account = NULL) {
  if (user_access('administer belpost', $account)) {
    return TRUE;
  }
  if ($op == 'view' && user_access('view belpost', $account)) {
    return TRUE;
  }
  return FALSE;
}

/**
 * Implements hook_permission().
 */
function belpost_permission() {
  return array(
    'view belpost' => array(
      'title' => t('View Belgian Postal Codes'),
      'description' => t('User can view Belgian Postal Codes'),
    ),
    'administer belpost' => array(
      'title' => t('Administer Belgian Postal Codes'),
      'description' => t('User can view,add, update and delete Belgian Postal Codes'),
    ),
  );
}

/**
 * Returns a belpost entity.
 * 
 * @param int $id 
 *   id of the entity
 * 
 * @return object 
 *   a belpost entity or null if entity not found
 */
function belpost_load($id) {
  $entities = entity_load('BelPost', array($id));
  return array_pop($entities);
}

/**
 * Returns a render array with postal code info.
 * 
 * @param object $postalcode 
 *   a BelPost entity
 * 
 * @return array 
 *   a render array
 */
function belpost_view_code($postalcode) {
  drupal_set_title($postalcode->city);
  $render = entity_view('BelPost', array($postalcode->id => $postalcode));
  return $render;
}

class BelPostEntity extends Entity {
  /**
   * Returns the default uri for this Postal code.
   * 
   * @return array
   *   The uri info
   */
  public function defaultUri() {
    return array('path' => 'belpost/' . $this->identifier());
  }
}

class BelPostEntityAPIController extends EntityAPIController {
  /**
   * Returns a render array for a Belpost entity.
   * 
   * @param object $entity 
   *   A Belpost entity
   * @param string $view_mode 
   *   The viewmode
   * @param string $langcode 
   *   The language code
   * @param array $content 
   *   Allows prepopulating the build content
   * 
   * @return array
   *   The render array
   */
  public function buildContent($entity, $view_mode = 'full', $langcode = NULL, $content = array()) {
    $build = parent::buildContent($entity, $view_mode, $langcode, $content);
    $city = '';
    if (variable_get('belpost_language', 'nl') == 'nl') {
      $city = check_plain($entity->citynl);
    }
    else {
      $city = check_plain($entity->cityfr);
    }
    $build['postalcode'] = array(
      '#type' => 'markup',
      '#prefix' => '<div>',
      '#markup' => check_plain($entity->code) . ' ' . $city,
      '#suffix' => '</div>',
    );
    return $build;
  }
}


/**
 * Implements hook_field_info().
 */
function belpost_field_info() {
  return array(
    'belpost_ref' => array(
      'label' => t('Belgian Postal Code'),
      'description' => t('A reference to a Belgian Postal Code'),
      'default_formatter' => 'belpost_ref_format',
      'default_widget' => 'belpost_ref_widget',
    ),
  );
}
/**
 * Implements hook_field_is_empty().
 */
function belpost_field_is_empty($item, $field) {
  return empty($item['ref_belpost_id']);
}

/**
 * Implements hook_field_formatter_info().
 */
function belpost_field_formatter_info() {
  return array(
    'belpost_ref_format' => array(
      'label' => t('Belgian Postal Code'),
      'field types' => array('belpost_ref'),
    ),
  );
}

/**
 * Implements hook_field_widget_info().
 */
function belpost_field_widget_info() {
  return array(
    'belpost_ref_widget' => array(
      'label' => t('Belgian Postal Code'),
      'field types' => array('belpost_ref'),
    ),
  );
}

/**
 * Implements hook_field_formatter_view().
 */
function belpost_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();
  switch ($display['type']) {
    case 'belpost_ref_format':
      foreach ($items as $delta => $item) {
        $postalcode = belpost_load($item['ref_belpost_id']);
        $element[$delta] = entity_view('BelPost', array($postalcode->id => $postalcode), 'field');
      }
      break;
  }
  return $element;
}

/**
 * Implements hook_field_widget_form().
 */
function belpost_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
  switch ($instance['widget']['type']) {
    case 'belpost_ref_widget':
      $value = empty($items[$delta]['ref_belpost_id']) ? '' : $items[$delta]['ref_belpost_id'];
      if (!empty($value) && is_numeric($value)) {
        $postalcode = entity_load_single('BelPost', $value);
        $city = '';
        if (variable_get('belpost_language', 'nl') == 'nl') {
          $city = $postalcode->citynl;
        }
        else {
          $city = $postalcode->cityfr;
        }
        $value = $postalcode->code . ' ' . $city;
      }
      $element['ref_belpost_id'] = array(
        '#title' => check_plain($element['#title']),
        '#type' => 'textfield',
        '#default_value' => $value,
        '#description' => check_plain($element['#description']),
        '#required' => $element['#required'],
        '#element_validate' => array('belpost_element_field_validate'),
        '#autocomplete_path' => 'belpost/autocomplete',
      );
      break;
  }
  return $element;
}

/**
 * Implements hook_theme_registry_alter().
 * 
 * Adds module path to the theme registry so belpost.tpl.php gets picked up.
 * See http://www.metachunk.com/blog/adding-module-path-drupal-7-theme-registry.
 */
function belpost_theme_registry_alter(&$theme_registry) {
  $mod_path = drupal_get_path('module', 'belpost');
  // Munge on a copy.
  $theme_registry_copy = $theme_registry;
  _theme_process_registry($theme_registry_copy, 'phptemplate', 'theme_engine', 'pow', $mod_path);
  $theme_registry += array_diff_key($theme_registry_copy, $theme_registry);
}

/**
 * Validates the input of the BelPost field.
 * 
 * @param array $element
 *   The form-element
 * @param array $form_state
 *   The form state
 * @param array $form
 *   The form
 */
function belpost_element_field_validate($element, &$form_state, $form) {
  if (!empty($element['#value'])) {
    $lijst = array();
    // Check for '<postalcode city>.
    if (preg_match('/^([0-9]{4}) (.+)$/', $element['#value'], $lijst)) {
      $query = new EntityFieldQuery();
      $query = $query->entityCondition('entity_type', 'BelPost')
              ->propertyCondition('code', $lijst[1])
              ->addTag('node_access');
      // Get the right language.
      $language = variable_get('belpost_language', 'nl');
      if ($language == 'nl') {
        $query = $query->propertyCondition('citynl', $lijst[2]);
      }
      else {
        $query = $query->propertyCondition('cityfr', $lijst[2]);
      }
      $result = $query->execute();
      // Check whether only one postal code is found.
      if (isset($result['BelPost']) && count($result['BelPost']) == 1) {
        $belpost_nids = array_keys($result['BelPost']);
        if (count($belpost_nids) == 1) {
          $value = array_pop($belpost_nids);
          form_set_value($element, $value, $form_state);
        }
        else {
          form_error($element, t('Combinatie "postcode gemeente" is niet uniek'));
        }
      }
      else {
        form_error($element, t('Combinatie "postcode gemeente" niet gevonden'));
      }
    }
    else {
      form_error($element, t('Dit is geen geldig postcode formaat(Postnummer Gemeente)'));
    }
  }
}

/**
 * Autocomplete function for Belpost field.
 * 
 * @param string $code
 *   The string to search for.
 */
function belpost_autocomplete($code) {
  $code = check_markup($code);
  $var = array();
  $language = variable_get('belpost_language', 'nl');
  // Only (partial) postal code is entered.
  if (is_numeric($code)) {
    $sql = '';
    if ($language == 'nl') {
      $sql = 'SELECT code, citynl FROM {belpost} WHERE code LIKE :code';
    }
    else {
      $sql = 'SELECT code, cityfr FROM {belpost} WHERE code LIKE :code';
    }
    $result = db_query_range($sql, 0, 10, array(':code' => $code . '%'));
    $rows = $result->fetchAll(PDO::FETCH_NUM);
    foreach ($rows as $row) {
      $var[$row[0] . ' ' . $row[1]] = $row[0] . ' ' . $row[1];
    }
  }
  else {
    $codecity = array();
    $code = urldecode($code);
    // Postal code and (partial) city is entered.
    if (preg_match('/^([0-9]{4}) (.+)$/', $code, $codecity)) {
      $sql = '';
      if ($language == 'nl') {
        $sql = 'SELECT code, citynl FROM {belpost} WHERE code = :code AND citynl LIKE :city';
      }
      else {
        $sql = 'SELECT code, cityfr FROM {belpost} WHERE code = :code AND cityfr LIKE :city';
      }
      $result = db_query_range($sql, 0, 10, array(':code' => $codecity[1], ':city' => $codecity[2] . '%'));
      $rows = $result->fetchAll(PDO::FETCH_NUM);
      foreach ($rows as $row) {
        $var[$row[0] . ' ' . $row[1]] = $row[0] . ' ' . $row[1];
      }
    }
    else {
      // Only (partial) city is entered.
      if ($language == 'nl') {
        $sql = 'SELECT code, citynl FROM {belpost} WHERE citynl LIKE :city';
      }
      else {
        $sql = 'SELECT code, cityfr FROM {belpost} WHERE cityfr LIKE :city';
      }
      $result = db_query_range($sql, 0, 10, array(':city' => $code . '%'));
      $rows = $result->fetchAll(PDO::FETCH_NUM);
      foreach ($rows as $row) {
        $var[$row[0] . ' ' . $row[1]] = $row[0] . ' ' . $row[1];
      }
    }
  }
  drupal_json_output($var);
}

/**
 * Build the configuration form.
 * 
 * @return array
 *   The configuration form.
 */
function belpost_admin() {
  $form = array();
  $form['settings']['belpost_language'] = array(
    '#type' => 'radios',
    '#title' => t('Language'),
    '#description' => t('Define the language setting for Belgian postal codes'),
    '#options' => array('nl' => t('Dutch'), 'fr' => t('French')),
    '#default_value' => variable_get('belpost_language', 'nl'),
  );
  return system_settings_form($form);
}

